data = {
    "Ariana": {
        "region2": {
            "Ariana Ville": {
                "Ariana": {"zip": "2080"},
                "Borj El Baccouche": {"zip": "2037"},
                "Centre Commercial Ikram": {"zip": "2037"},
                "Cité Belvedere 2": {"zip": "2091"},
                "Cité Borj Turki 1": {"zip": "2058"},
                "Cité Borj Turki 2": {"zip": "2058"},
                "Cité des Roses": {"zip": "2080"},
                "Cité du Jardin": {"zip": "	2080"},
                "Cité du Printemps": {"zip": "2080"},
                "Cité du Soleil": {"zip": "2091"},
                "Cité El Intissar 1": {"zip": "2091"},
                "Cité El Intissar 2": {"zip": "2091"},
                "Cité Ennasr 1": {"zip": "2037"},
                "Cité Ennasr 2": {"zip": "2037"},
                "Cité Ennouzha": {"zip": "2080"},
                "Cité Essaada (ariana)": {"zip": "2080"},
                "Cité Essaada (riadh Andalous)": {"zip": "2058"},
                "Cité Jaafar": {"zip": "2080"},
                "Cité Jamil": {"zip": "2091"},
                "Cité Karim": {"zip": "2058"},
                "Cité Mehrzia 1": {"zip": "2058"},
                "El Menzah 5": {"zip": "2091"},
                "El Menzah 6": {"zip": "2091"},
                "El Menzah 7": {"zip": "2037"},
                "El Menzah 8": {"zip": "2037"},
                "Nouvelle Ariana": {"zip": "2080"},
                "Résidence El Ouns": {"zip": "2058"},
                "Résidence Ennour ( Naser 1)": {"zip": "2037"},
                "Résidence Ennour ( Naser 2)": {"zip": "2037"},
                "Résidence Ennour (ariana)": {"zip": "2080"},
                "Résidence Ibn Zeidoun": {"zip": "2058"},
                "Résidence Ichbilia": {"zip": "2058"},
                "Résidence Kortoba": {"zip": "2058"},
                "Riadh Landlous": {"zip": "2058"},

            },
            "Ettadhamen": {
                "Cité 18 Janvier": {"zip:2041"},
                "Cité Ben Yerfes": {"zip:2041"},
                "Cité El Houda": {"zip:2041"},
                "Cité Ennasser": {"zip:2041"},
                "Cité Ettadhamen": {"zip:2041"},
                "Cité Ettayarene": {"zip:2041"},
                "Cité Sfar": {"zip:2041"},
                "Cité Snit 2": {"zip:2041"},
                "Cité Snit Nagra": {"zip:2041"},

            },
            "Kalaat Landlous": {
                "Borj El Hadj": {"zip:2061"},
                "Cité Bir El Araies": {"zip:2022"},
                "Cité des Martyrs": {"zip:2022"},
                "Cité El Fejja": {"zip:2022"},
                "Cité El Mourouj": {"zip:2022"},
                "Cité El Oulja": {"zip:2022"},
                "Cité Essibous": {"zip:2022"},
                "Cité Tarek Ibn Zied": {"zip:2022"},
                "El Misra": {"zip:2061"},
                "Ferme Hababou": {"zip:2061"},
                "Ferme Mustapha": {"zip:2061"},
                "Henchir Toubias": {"zip:2061"},
                "Kalaat Landlous": {"zip:2022"},
                "Pont de Bizerte": {"zip:2061"},

            },
            "La Soukra": {
                "Aéroport Tunis Carthage": {"zip": "2035"},
                "Borj Louzir": {"zip": "2073"},
                "Charguia 1": {"zip": "2035"},
                "Charguia 2": {"zip": "2035"},
                "Chotrana 1": {"zip": "2036"},
                "Chotrana 2": {"zip": "2036"},
                "Chotrana 3": {"zip": "2036"},
                "Cité Astree": {"zip": "2036"},
                "Cité Belabla": {"zip": "2036"},
                "Cité Ben Hessine": {"zip": "2036"},
                "Cité Ben Kilani": {"zip": "2073"},
                "Cité Bou Fares": {"zip": "2036"},
                "Cité Chouachia": {"zip": "2036"},
                "Cité Chouchene": {"zip": "2036"},
                "Cité de l'aéroport": {"zip": "2036"},
                "Cité de la Sante": {"zip": "2073"},
                "Cité de la Terre Libre": {"zip": "2036"},
                "Cité des Juges": {"zip": "2036"},
                "Cité El Azzef": {"zip": "2036"},
                "Cité El Behi Ladghem": {"zip": "2073"},
                "Cité El Boustene 1": {"zip": "2036"},
                "Cité El Boustene 2": {"zip": "2036"},
                "Cité El Feth": {"zip": "2073"},
                "Cité El Hana": {"zip": "2073"},
                "Cité El Henaya": {"zip": "2036"},
                "Cité El Maid": {"zip": "2036"},
                "Cité El Mansoura": {"zip": "2073"},
                "Cité El Ouroud": {"zip": "2073"},
                "Cité Elyes": {"zip": "2036"},
                "Cité Ennacim": {"zip": "2073"},
                "Cité Ennouzha 3": {"zip": "2073"},
                "Cité Ettaamir": {"zip": "2036"},
                "Cité Ettaamir 5": {"zip": "2073"},
                "Cité Ezzitoun 1": {"zip": "2036"},
                "Cité Ezzitoun 2": {"zip": "2036"},
                "Cité Ezzouaidia": {"zip": "2036"},
                "Cité Farhat": {"zip": "2036"},
                "Cité Fateh": {"zip": "2036"},
                "Cité Fonciere": {"zip": "2036"},
                "Cité Ghouzaila": {"zip": "2073"},
                "Cité Hedi Nouira": {"zip": "2073"},
                "Cité Jebira": {"zip": "2073"},
                "Cité Snit": {"zip": "2073"},
                "Cité Star": {"zip": "2073"},
                "Cité Touilia": {"zip": "2036"},
                "Dar Fadhal": {"zip": "2036"},
                "La Soukra": {"zip": "2036"},
                "Mosque Erraoudha": {"zip": "2036"},
                "Résidence 26-26": {"zip": "2036"},
                "Résidence Ahlem": {"zip": "2036"},
                "Résidence El Ouns": {"zip": "2073"},
                "Résidence Ennesrine": {"zip": "2073"},
                "Résidence Meriem": {"zip": "2036"},
                "Sidi Frej": {"zip": "2036"},
                "Sidi Salah": {"zip": "2036"},
                "Sidi Soufiene": {"zip": "2036"},
                "Station Marchandises Fret": {"zip": "2035"},
                "Village Essahli": {"zip": "2036"},

            },
            "Mnihla": {
                "Cité Ali Bourguiba": {"zip": "2094"},
                "Cité de la Republique": {"zip": "2094"},
                "Cité El Bassatine1": {"zip": "2094"},
                "Cité El Bassatine2": {"zip": "2094"},
                "Cité El Bassatine3": {"zip": "2094"},
                "Cité El Gouabsia": {"zip": "2094"},
                "Cité El Ouard": {"zip": "2094"},
                "Cité Ennasr": {"zip": "2094"},
                "Cité Essaada": {"zip": "2094"},
                "Cité Rafaha": {"zip": "2094"},
                "Cité Rous El Harayek": {"zip": "2094"},
                "Mnihla": {"zip": "2094"},
                "Résidence Ennasr": {"zip": "2094"},

            },
            "Raoued": {
                "Ariana Essoughra": {"zip": "2081"},
                "Borj Touil": {"zip": "2081"},
                "Bou Hnech": {"zip": "2081"},
                "Cité 7 Novembre": {"zip": "2056"},
                "Cité aéroport": {"zip": "2056"},
                "Cité Chaker": {"zip": "2081"},
                "Cité Chargui": {"zip": "2056"},
                "Cité de la Mosque": {"zip": "2081"},
                "Cité de la Rtt 2": {"zip": "2083"},
                "Cité des Juges": {"zip": "2056"},
                "Cité El Abadla": {"zip": "2083"},
                "Cité El Amel": {"zip": "2083"},
                "Cité El Ghazala 1": {"zip": "2083"},
                "Cité El Ghazala 2": {"zip": "2083"},
                "Cité El Mouaouiet": {"zip": "2081"},
                "Cité El Mountazeh": {"zip": "2081"},
                "Cité El Wafa": {"zip": "2083"},
                "Cité El Yamama": {"zip": "2056"},
                "Cité Ennasr": {"zip": "2083"},
                "Cité Ennkhilet": {"zip": "2083"},
                "Cité Ennour Jaafar": {"zip": "2081"},
                "Cité Erriadh": {"zip": "2081"},
                "Cité Essaada": {"zip": "2081"},
                "Cité Essahafa": {"zip": "2083"},
                "Cité Ibn Rachik": {"zip": "2083"},
                "Cité Mehrzia 2": {"zip": "2083"},
                "Cité Sidi Salah": {"zip": "2056"},
                "Cité Sidi Slimene": {"zip": "2081"},
                "Cité Snit": {"zip": "2081"},
                "Cité Zghab": {"zip": "2056"},
                "Complexe Technologique": {"zip": "2088"},
                "Douar El Hendi": {"zip": "2081"},
                "El Brarja": {"zip": "2056"},
                "El Hessiene": {"zip": "2081"},
                "Jaafar 1": {"zip": "2083"},
                "Jaafar 2": {"zip": "2083"},
                "Oued El Khayat": {"zip": "2081"},
                "Oued El Makhzen": {"zip": "2081"},
                "Raoued": {"zip": "2056"},
                "Résidence El Ayech": {"zip": "2081"},
                "Résidence El Ouns": {"zip": "2081"},
                "Résidence Ennarjes": {"zip": "2081"},
                "Résidence Essalem": {"zip": "2081"},
                "Résidence Rim": {"zip": "2081"},
                "Route Ezzaouia": {"zip": "2081"},

            },
            "Sidi Thabet": {
                "Bejaoua 2": {"zip": "2020"},
                "Borj El Khoukha": {"zip": "2032"},
                "Borj Youssef": {"zip": "2032"},
                "Cebalet Ben Ammar": {"zip": "2032"},
                "Chorfech": {"zip": "2057"},
                "Chorfech 12": {"zip": "2032"},
                "Chorfech 2": {"zip": "2057"},
                "Chorfech 24": {"zip": "2057"},
                "Chorfech 8": {"zip": "2057"},
                "Cité 18 Janvier": {"zip": "2020"},
                "Cité Afh": {"zip": "2020"},
                "Cité des Agriculteurs": {"zip": "2020"},
                "Cité des Oranges": {"zip": "2020"},
                "Cité Dridi": {"zip": "2032"},
                "Cité El Bokri": {"zip": "2032"},
                "Cité El Frachich": {"zip": "2032"},
                "Cité El Ghribi": {"zip": "2032"},
                "Cité El Gouazine": {"zip": "2020"},
                "Cité El Mbarka": {"zip": "2020"},
                "Cité El Methalithe": {"zip": "2032"},
                "Cité El Mrezgua": {"zip": "2020"},
                "Cité Essaada": {"zip": "2020"},
                "Cité Ettbaieb": {"zip": "2020"},
                "Cité Jardins": {"zip": "2020"},
                "Cité Messouda": {"zip": "2032"},
                "Cité Mongi Slim": {"zip": "2020"},
                "Cité Ouvriere": {"zip": "2032"},
                "Cité Sidi Marouane": {"zip": "2032"},
                "Ezzaouia": {"zip": "2032"},
                "Jabbes": {"zip": "2032"},
                "Jabbes El Borj": {"zip": "2032"},
                "Sidi Thabet": {"zip": "2020"},

            }
        }
    },
    "Beja": {
        "region2": {
            "Amdoun": {
                "Adailia": {"zip": "9030"},
                "Ain El Goussa": {"zip": "9030"},
                "Ain Ghenem": {"zip": "9030"},

            }
        }
    }

}

ville_list = (data['Ariana']['region2'].keys())

dict = {

}
for i, item in enumerate(ville_list):
    dict[i+1] = item

print(dict)
